# Generated by Django 4.2.11 on 2025-01-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calls_handled', models.IntegerField(default=0)),
                ('average_duration', models.FloatField(default=0.0)),
                ('satisfaction_score_avg', models.FloatField(default=0.0)),
                ('response_time_avg', models.FloatField(default=0.0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='api.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AIInteractionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ai_calls_handled', models.IntegerField(default=0)),
                ('ai_success_rate', models.FloatField(default=0.0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('handoff_count', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_metrics', to='api.agent')),
            ],
        ),
        migrations.CreateModel(
            name='CallPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calls', models.IntegerField(default=0)),
                ('completed_calls', models.IntegerField(default=0)),
                ('missed_calls', models.IntegerField(default=0)),
                ('average_call_duration', models.FloatField(default=0.0)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_performance', to='api.agent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_performance', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CallTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('peak_hours', models.CharField(max_length=255)),
                ('total_calls', models.IntegerField(default=0)),
                ('inbound_calls', models.IntegerField(default=0)),
                ('outbound_calls', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_trends', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_score', models.IntegerField()),
                ('sentiment_score', models.FloatField()),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction', to='api.call')),
            ],
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='organization',
        ),
        migrations.DeleteModel(
            name='AgentConfiguration',
        ),
        migrations.DeleteModel(
            name='Analytics',
        ),
    ]
