# Generated by Django 4.2.11 on 2025-01-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agentperformance_aiinteractionmetrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_level_percentage', models.FloatField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_level', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DetailedCallAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_category', models.CharField(max_length=255)),
                ('resolution_time', models.FloatField(default=0.0)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_analytics', to='api.call')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calls', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_analytics', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_queue_length', models.IntegerField(default=0)),
                ('average_queue_length', models.IntegerField(default=0)),
                ('average_wait_time', models.FloatField(default=0.0)),
                ('abandoned_calls', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_queue', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AgentInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_start_time', models.DateTimeField()),
                ('interaction_end_time', models.DateTimeField(blank=True, null=True)),
                ('interaction_type', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to='api.agent')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to='api.call')),
            ],
        ),
    ]
