# Generated by Django 4.2.11 on 2025-01-07 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadGeneration',
            fields=[
                ('LeadID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('PhoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('CompanyName', models.CharField(blank=True, max_length=100, null=True)),
                ('JobTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('LeadSource', models.CharField(blank=True, max_length=100, null=True)),
                ('LeadStatus', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Lost', 'Lost')], default='New', max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderConfirmation',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('ProductID', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentStatus', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('OrderStatus', models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('LeadID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.leadgeneration')),
            ],
        ),
    ]
