# Generated by Django 5.1.5 on 2025-03-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_client_created_at_alter_client_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductName', models.CharField(max_length=50)),
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField()),
                ('ClientPhone', models.CharField(blank=True, max_length=15, null=True)),
                ('ClientName', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.IntegerField()),
                ('OrderID', models.IntegerField()),
            ],
        ),
    ]
